sudo: required
dist: trusty
language: node_js
node_js:
  - '6.5'
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install -g typedoc
- npm install -g reflect-metadata
- npm install
- npm install -g surge

script:
- ng build --prod --aot

deploy:
  provider: surge
  skip_cleanup: true
  project: ./dist/ # specify the folder from which you want to push your code.
  domain: angulardemo.surge.sh # your surge.sh domain name

branches:
  only:
    - develop
